export const FETCH_INFOBYCOUNTURY = 'FETCH_INFOBYCOUNTURY';
export const FETCH_INFOBYCOUNTURY_SUCCESSED = 'FETCH_INFOBYCOUNTURY_SUCCESSED';
export const FETCH_INFOBYCOUNTURY_FAILED = 'FETCH_INFOBYCOUNTURY_FAILED';
