export const FETCH_INFOBYCOUNTURY = 'FETCH_INFOBYCOUNTURY';
export const FETCH_INFOBYCOUNTURY_SUCCESSED = 'FETCH_INFOBYCOUNTURY_SUCCESSED';
export const FETCH_INFOBYCOUNTURY_FAILED = 'FETCH_INFOBYCOUNTURY_FAILED';

export const ADD_REPORT_SUBMIT = 'ADD_REPORT_SUBMIT';
export const ADD_REPORT_SUBMIT_SUCCESSED = 'ADD_REPORT_SUBMIT_SUCCESSED';
export const ADD_REPORT_SUBMIT_FAILED = 'ADD_REPORT_SUBMIT_FAILED';
