export const FETCH_INFOBYCOUNTURY = 'FETCH_INFOBYCOUNTURY';
export const FETCH_INFOBYCOUNTURY_SUCCESSED = 'FETCH_INFOBYCOUNTURY_SUCCESSED';
export const FETCH_INFOBYCOUNTURY_FAILED = 'FETCH_INFOBYCOUNTURY_FAILED';

export const ADD_REPORT_SUBMIT = 'ADD_REPORT_SUBMIT';
export const ADD_REPORT_SUBMIT_SUCCESSED = 'ADD_REPORT_SUBMIT_SUCCESSED';
export const ADD_REPORT_SUBMIT_FAILED = 'ADD_REPORT_SUBMIT_FAILED';

export const FETCH_CONFIRMEDINFO = 'FETCH_CONFIRMEDINFO';
export const FETCH_CONFIRMEDINFO_SUCCESSED = 'FETCH_CONFIRMEDINFO_SUCCESSED';
export const FETCH_CONFIRMEDINFO_FAILED = 'FETCH_INFOBYCOUNTURY_FAILED';

export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const GET_CURRENT_LOCATION_SUCCESSED = 'GET_CURRENT_LOCATION_SUCCESSED';
export const GET_CURRENT_LOCATION_FAILED = 'GET_CURRENT_LOCATION_FAILED';

export const FETCH_INFOBYCOUNTURY_FIREBASE = 'FETCH_INFOBYCOUNTURY_FIREBASE';
export const FETCH_INFOBYCOUNTURY__FIREBASE_SUCCESSED = 'FETCH_INFOBYCOUNTURY__FIREBASE_SUCCESSED';
export const FETCH_INFOBYCOUNTURY__FIREBASE_FAILED = 'FETCH_INFOBYCOUNTURY__FIREBASE_FAILED';
